# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/18740/Desktop/Project_Vivado/rom_conv1_w/vivado_project/rom.srcs/sources_1/ip/rom_conv1_w_32x864/rom_conv1_w_32x864.xci
# IP: The module: 'rom_conv1_w_32x864' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18740/Desktop/Project_Vivado/rom_conv1_w/vivado_project/rom.srcs/sources_1/ip/rom_conv1_w_32x864/rom_conv1_w_32x864_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_conv1_w_32x864'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/18740/Desktop/Project_Vivado/rom_conv1_w/vivado_project/rom.srcs/sources_1/ip/rom_conv1_w_32x864/rom_conv1_w_32x864.xci
# IP: The module: 'rom_conv1_w_32x864' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18740/Desktop/Project_Vivado/rom_conv1_w/vivado_project/rom.srcs/sources_1/ip/rom_conv1_w_32x864/rom_conv1_w_32x864_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_conv1_w_32x864'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
