# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/18740/Desktop/Project_Vivado/floating point IP cores/floating point IP cores.srcs/sources_1/ip/floating_point_add_and_sub/floating_point_add_and_sub.xci
# IP: The module: 'floating_point_add_and_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18740/Desktop/Project_Vivado/floating point IP cores/floating point IP cores.srcs/sources_1/ip/floating_point_add_and_sub/floating_point_add_and_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_add_and_sub'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/18740/Desktop/Project_Vivado/floating point IP cores/floating point IP cores.srcs/sources_1/ip/floating_point_add_and_sub/floating_point_add_and_sub.xci
# IP: The module: 'floating_point_add_and_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18740/Desktop/Project_Vivado/floating point IP cores/floating point IP cores.srcs/sources_1/ip/floating_point_add_and_sub/floating_point_add_and_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_add_and_sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
